gcp:
  project_id: "ai-hack-2026-winson"
  region: "us-central1"
  default_zone: "us-central1-a"

thresholds:
  cpu_critical: 90
  cpu_warning: 80
  disk_critical: 90
  disk_warning: 80


gcs_bucket: "ai-hack-2026-winson-inspection"

budget:
  daily_max_usd: 3.0

inspection:
  zones:
    - "us-central1-a"
